name: SonarQube Scan

on:
  push:
    branches:
      - master

jobs:
  sonar-scanner:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Check out code
        uses: actions/checkout@v4

      # Step 2: Run SonarQube Scan
      - name: Run SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v3
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}